version: '3.8'

services:
  # SQL Server Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carborrow-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./backend/CreateDatabase.sql:/docker-entrypoint-initdb.d/CreateDatabase.sql
    networks:
      - carborrow-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  # Backend ASP.NET Core API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carborrow-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=database;Database=CarRentalDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - carborrow-network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./car-rent-frontend
      dockerfile: Dockerfile
    container_name: carborrow-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - carborrow-network
    restart: unless-stopped

networks:
  carborrow-network:
    driver: bridge

volumes:
  sqlserver_data:
